# Generated by Django 5.2.3 on 2025-10-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.AddField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop',
            field=models.CharField(blank=True, choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('tomato', 'Tomato'), ('potato', 'Potato'), ('onion', 'Onion'), ('maize', 'Maize'), ('sugarcane', 'Sugarcane'), ('cotton', 'Cotton'), ('soybean', 'Soybean'), ('barley', 'Barley')], max_length=50, null=True),
        ),
    ]
